### ISSUE TITLE
add a minTime option to limit request rate

### ISSUE THREAD

**Issue by leeoniya** [lukeed/throttles#2]
@lukeed 

e.g. from https://github.com/SGrondin/bottleneck#quick-start

```js
const limiter = new Bottleneck({
  maxConcurrent: 1,
  minTime: 333
});
```

TBH, without a `minTime` parameter i'm not sure how this lib can be called a throttler. e.g. i can set concurrency to 1 but still uncontrollably hammer a server with http requests if each request takes 75ms.

**Comment by lukeed** [comment]
Hey,

That's kinda silly TBH. What about a 2G vs 4G network? A `minTime` becomes irrelevant.
Instead, you need to tell the instance when a function is complete (or when you _consider_ it complete) regardless of its duration. 

If you want to throttle HTTP request _invocations_, that's basically a synchronous operation & you can manage that easily on a true-definition of `throttle`, since you restrict X calls every Y time.

But if you want to manage HTTP request _completions_, that's a different behavior entirely. That's asynchronous and network dependent. Concurrency is easily controlled here, but `interval` mostly affects the _next_ cycle, since your functions' duration won't align with the interval.

Both scenarios are allowed with `throttles`, since it's purely up to you when an item is marked as complete.

```js
send(); isDone();
// vs
send().finally(isDone);
```

**Comment by lukeed** [comment]
Deleted my own comment because I was conflating `throttles` with `saturated` since they started out as part of the same library 😆 

You may be interested in [`saturated`](https://github.com/lukeed/saturated) instead for your use case, as it deals with intervals and concurrency. This `throttles` is meant for concurrency control _only_.

**Comment by leeoniya** [comment]
ah, thanks!
